# H3 Tiles

## Load General Libraries
```{r}
library(tidyverse)
library(sf)
library(ggmap)
```

## Read in Data
```{r}
# read in RDS
lines.sf <- readRDS("data/10x/lines_sf.rds")
buses.sf <- readRDS("data/10x/buses_sf.rds")
map <- readRDS("data/10x/map_stadia_z14.rds")

# get the bounding box of map
left <- attr(map, "bb")$ll.lon
right <- attr(map, "bb")$ur.lon
bottom <- attr(map, "bb")$ll.lat
top <- attr(map, "bb")$ur.lat
```

## Load H3 Libraries
```{r}
library(h3jsr)
```

## Create Hex Map with H3
```{r}
# set crs
st_crs(buses.sf$geometry) <- 4326
# check for any rows in buses.sf that have a non-numeric value in the voltage column
buses.sf$voltage <- as.numeric(as.character(buses.sf$voltage))
# drop buses with NA voltage
buses.sf <- buses.sf %>% filter(!is.na(voltage)) # drops 248 buses

# get h3 id for each
# loop over resolutions 8-12
min_res <- 8
max_res <- 12
for (res in min_res:max_res) {
  h3_col <- paste0("h3r", res)
  buses.sf <- buses.sf %>% mutate(!!h3_col := point_to_cell(geometry, res = res, simple = TRUE))
}
glimpse(buses.sf)

# aggregate for each resolution
# loop fromo min_res to max_res
buses.h3 <- list()
for (res in min_res:max_res) {
  h3_col <- paste0("h3r", res)
  buses.h3[[res]] <- buses.sf %>% group_by(!!sym(h3_col)) %>% summarise(
    avg = mean(voltage, na.rm = TRUE),
    stddev = sd(voltage, na.rm = TRUE),
    count = n(),
    res = res
  ) %>% rename(h3 = !!sym(h3_col), voltage = avg)
}
# combine all resolutions
buses.h3 <- do.call(rbind, buses.h3)
# update geometry from MultiPoint to Polygon
buses.h3$geometry <- cell_to_polygon(buses.h3$h3)
# add a column "area" with the area of each hex polygon
buses.h3$area <- st_area(buses.h3$geometry)
# inspect before exporting
glimpse(buses.h3)
# export
saveRDS(buses.h3, "data/10x/buses_h3_r8to12.rds")
```

## Visualize Hexes
```{r}
# import buses.h3 and lines
buses.h3 <- readRDS("data/10x/buses_h3_r8to12.rds")
# plot just desired resolutions
buses.h3 <- buses.h3 %>% filter(res == 12)
glimpse(buses.h3)

# plot it
h3plot <- ggmap(map) +
  geom_sf(
    data = buses.h3, 
    aes(fill = voltage, color = voltage),
    alpha = 1.0,
    inherit.aes = FALSE
  ) +
  # geom_sf(
  #   data = lines.sf, 
  #   color="black", 
  #   alpha = 0.05, 
  #   inherit.aes = FALSE
  # ) +
  scale_fill_gradient2(
    low = "darkblue",
    mid = "white",
    high = "darkred",
    midpoint = 1,
    limits = c(0.95, 1.05),
    space = "Lab",
    guide = "colourbar",
    aesthetics = "fill",
    oob = scales::squish 
  ) +
  scale_color_gradient2(
    low = "darkblue",
    mid = "white",
    high = "darkred",
    midpoint = 1,
    limits = c(0.95, 1.05),
    space = "Lab",
    guide = "colourbar",
    aesthetics = "color",
    oob = scales::squish
  ) +
  theme(
    legend.position = c(0.96, 0.15),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),    
    text = element_text(family = "Serif", size = 18)
  ) +
  coord_sf(xlim = c(left, right), ylim = c(bottom, top))

ggsave(
  filename = "10x/figures/h3_plot_r12.png", 
  h3plot,
  width = 6480,
  height = 6480,
  dpi = 300,
  units = "px",
  device = "png",
  limitsize = FALSE
)
```


## Distribution Plot V2 for Single-Res Hexes
```{r}
# read in data
buses.sf <- readRDS("data/10x/buses_sf.rds")
buses.h3 <- readRDS("data/10x/buses_h3.rds")

# keep just plotted resolution
# buses.h3 <- buses.h3 %>% filter(res == 11)

# plot distribution of voltages against normal voltages
ggplot() +
  geom_density(
    data = buses.sf,
    aes(x = voltage, fill = "Actual"),
    color = "forestgreen",
    alpha = 0.15,
    adjust = 3,
    size = 1.5
  ) +
  geom_density(
    data = buses.h3,
    aes(x = voltage, weight = area, fill = "Plotted"),
    color = "#cbad03",
    alpha = 0.35,
    adjust = 3,
    size = 1.5
  ) +
  xlim(0.995, 1.04) +
  scale_fill_manual(
    name = element_blank(),
    values = c("Actual" = "forestgreen", "Plotted" = "gold")
  ) +
  labs(
    x = "Voltage [p.u.]",
    y = "Density"
  ) +
  theme(
    legend.position = c(0.9, 0.5),
    legend.background = element_rect(fill = "transparent"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.background = element_blank(),
    text = element_text(family = "Serif", size = 24)
  )
```

## Filter Out High Variance Hexes for Multi-Res
```{r}
# define large and small hexes
h3_res_low <- 9
h3_res_med <- 10
h3_res_hi <- 11
h3_res_vhi <- 12

h3_std_dev_max <- 0.003

# read in hexes
buses.h3 <- readRDS("data/10x/buses_h3.rds")
lines.sf <- readRDS("data/10x/lines_sf.rds")

# filter out hexes with high variance
buses.h3.low <- buses.h3 %>% 
  filter(res == h3_res_low)

buses.h3.filt.low <- buses.h3 %>% 
  filter(res == h3_res_low & stddev < h3_std_dev_max)

buses.h3.filt.med <- buses.h3 %>%
  filter(res == h3_res_med & stddev < h3_std_dev_max) %>%
  filter(!(h3jsr::get_parent(h3, h3_res_low) %in% buses.h3.filt.low$h3))

buses.h3.filt.hi <- buses.h3 %>%
  filter(res == h3_res_hi) %>%
  filter(!(h3jsr::get_parent(h3, h3_res_low) %in% buses.h3.filt.low$h3)) %>%
  filter(!(h3jsr::get_parent(h3, h3_res_med) %in% buses.h3.filt.med$h3))

buses.h3.filt.vhi <- buses.h3 %>%
  filter(res == h3_res_vhi) %>%
  filter(!(h3jsr::get_parent(h3, h3_res_low) %in% buses.h3.filt.low$h3)) %>%
  filter(!(h3jsr::get_parent(h3, h3_res_med) %in% buses.h3.filt.med$h3)) %>%
  filter(!(h3jsr::get_parent(h3, h3_res_hi) %in% buses.h3.filt.hi$h3))

# recombine hexes
buses.h3.filt <- rbind(buses.h3.low, buses.h3.filt.med, buses.h3.filt.hi, buses.h3.filt.vhi)
buses.h3.filt.true <- rbind(buses.h3.filt.low, buses.h3.filt.med, buses.h3.filt.hi, buses.h3.filt.vhi)
# rm(buses.h3.low, buses.h3.med, buses.h3.hi)

# export filtered hexes
saveRDS(buses.h3.filt, "data/10x/buses_h3_filt.rds")
saveRDS(buses.h3.filt.true, "data/10x/buses_h3_filt_true.rds")
```

## Plot Multi-Res Hexes
```{r}
# import buses.h3 and lines
buses.h3.filt <- readRDS("data/10x/buses_h3_filt.rds")
lines.sf <- readRDS("data/10x/lines_sf.rds")

# plot multi-res
plot.base <- ggplot() + theme_bw()
plot.lines <- geom_sf(data = lines.sf, color="black", alpha = 0.1)

plot.hex.multires <- plot.base +
  geom_sf(data = buses.h3.filt, aes(fill = voltage), color = NA) +
  scale_fill_gradient2(
    low = "darkblue",
    mid = "white",
    high = "darkred",
    midpoint = 1,
    limits = c(0.95, 1.05),
    space = "Lab",
    guide = "colourbar",
    aesthetics = "fill",
    oob = scales::squish
  ) +
  plot.lines

plot.hex.multires + ggtitle("Voltage Hexes at Multiple Resolutions & Lines, Res 8-10")
```

## Redo Multi-Res Hexmap for Paper
```{r}
# import buses.h3 and lines
buses.h3.filt <- readRDS("data/10x/buses_h3_filt.rds")
lines.sf <- readRDS("data/10x/lines_sf.rds")

# plot it
h3_plot <- ggmap(map) +
  geom_sf(
    data = buses.h3.filt, 
    aes(fill = voltage, color = voltage),
    alpha = 1.0,
    inherit.aes = FALSE
  ) +
  geom_sf(
    data = lines.sf, 
    color="black", 
    alpha = 0.05, 
    inherit.aes = FALSE
  ) +
  scale_fill_gradient2(
    low = "darkblue",
    mid = "white",
    high = "darkred",
    midpoint = 1,
    limits = c(0.95, 1.05),
    space = "Lab",
    guide = "colourbar",
    aesthetics = "fill",
    oob = scales::squish 
  ) +
  scale_color_gradient2(
    low = "darkblue",
    mid = "white",
    high = "darkred",
    midpoint = 1,
    limits = c(0.95, 1.05),
    space = "Lab",
    guide = "colourbar",
    aesthetics = "color",
    oob = scales::squish
  ) +
  theme(
    legend.position = c(0.96, 0.15),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    text = element_text(family = "Serif", size = 18)
  ) +
  coord_sf(xlim = c(left, right), ylim = c(bottom, top))
```


## Distribution Plot for Multi-Res Hex
```{r}
# import filtered hexes
# import buses.sf
buses.sf <- readRDS("data/10x/buses_sf.rds")
buses.h3.filt <- readRDS("data/10x/buses_h3_filt.rds")

# calculate the area of each polygon in hex.sf into a column area
buses.h3.filt <- buses.h3.filt %>% mutate(area = drop_units(st_area(geometry)))
# create a new column voltage.rounded that rounds voltage to the nearest 0.001
buses.h3.filt <- buses.h3.filt %>% mutate(voltage.rounded = round(voltage, 3))

# plot distribution of voltages against normal voltages
ggplot() +
  geom_density(
    data = buses.h3.filt %>% filter(voltage > 0.99 & voltage < 1.04),
    aes(x = voltage.rounded, weight = area),
    fill = "gold",
    color = "gold",
    alpha = 0.5,
    show.legend = TRUE,
    adjust = 1
  ) +
  geom_density(
    data = buses.sf %>% filter(voltage > 0.99 & voltage < 1.04),
     aes(x = voltage, fill = voltage),
    fill = "lightblue",
    color = "lightblue",
    alpha = 0.5,
    show.legend = TRUE,
    adjust = 1
  ) +
  ggtitle("Distribution of Voltages in Actual Buses vs Multi-Res Hex Map, Res 8 & 10") + 
  theme_bw()
```

## Distribution Plot V2 for Hexes
```{r}
# read in data
buses.sf <- readRDS("data/10x/buses_sf.rds")
buses.h3 <- readRDS("data/10x/buses_h3.rds")

# calculate the area of each polygon in hex.sf into a column area
buses.h3 <- buses.h3 %>% mutate(area = drop_units(st_area(geometry)))
# create a new column voltage.rounded that rounds voltage to the nearest 0.001
buses.h3 <- buses.h3 %>% mutate(voltage.rounded = round(voltage, 3))

# plot distribution of voltages against normal voltages
ggplot() +
  geom_density(
    data = buses.sf,
    aes(x = voltage, fill = "Actual"),
    color = "forestgreen",
    alpha = 0.15,
    adjust = 3,
    size = 1.5
  ) +
  geom_density(
    data = buses.h3,
    aes(x = voltage.rounded, weight = area, fill = "Plotted"),
    color = "#cbad03",
    alpha = 0.35,
    adjust = 3,
    size = 1.5
  ) +
  xlim(0.995, 1.04) +
  scale_fill_manual(
    name = element_blank(),
    values = c("Actual" = "forestgreen", "Plotted" = "gold")
  ) +
  labs(
    x = "Voltage [p.u.]",
    y = "Density"
  ) +
  theme(
    legend.position = c(0.9, 0.5),
    legend.background = element_rect(fill = "transparent"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.background = element_blank(),
    text = element_text(family = "Serif", size = 24)
  )
```

## Compute Statistics for Hexes
```{r}
# read in data
buses.sf <- readRDS("data/10x/buses_sf.rds")
buses.h3 <- readRDS("data/10x/buses_h3.rds")
buses.h3 <- buses.h3 %>% filter(res >= 10 & res <= 12)

# normalize area column
buses.h3$area_norm <- buses.h3$area / sum(buses.h3$area)
set.seed(44)
voltage_sample_h3 <- sample(buses.h3$voltage, 10*nrow(buses.h3), replace = TRUE, prob = buses.h3$area_norm)

# stats
(median(voltage_sample_h3))
(ks.test(buses.sf$voltage, voltage_sample_h3))
(IQR(voltage_sample_h3))
(var(voltage_sample_h3))
(sd(voltage_sample_h3))
(min(buses.h3$voltage))
(max(buses.h3$voltage))
(kurtosis(voltage_sample_h3))

#  show me the 10 buses with the highest voltages out of buses.df
# but just the columns h3 and voltage and count
head(arrange(buses.h3, desc(voltage))$h3, 10)

# find the buses in buses.sf contained within hex 8c283098ab001ff
buses.sf %>% filter(h3r12 == "8c283098ab001ff")

# visuals
boxplot(voltage_sample_h3)
hist(voltage_sample_h3)
```

## Vioplot for Hexes
```{r}
# violin plot
library(vioplot)

par(family = "serif", cex = 1.2)
vioplot(buses.sf$voltage, ylim=c(0.94,1.07), side="left", at=0.97, xaxt='n', yaxt='n', horizontal = TRUE, col = "#929cfc")
vioplot(voltage_sample_h3, ylim=c(0.94,1.07), side="right", at=1.03, add=TRUE, horizontal = TRUE, col = "#fda99c")
title(xlab = "Voltage [p.u.]")
axis(1, at=c(0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.0, 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07))
axis(2, at=c(0.75, 1.25), tick=FALSE, labels = c("Actual", "| Visualized"))
abline(v=1.05, lty=2)
abline(v=.95, lty=2)
# abline(h=1, lty=1)
```