---
title: "tiling"
author: "Isaiah Lyons-Galante"
date: "2023-05-08"
output: html_document
---

# Load Libraries
```{r}
library(tidyverse) # for data reading and processing
library(ggmap) # for getting map backgrounds
library(sf) # for converting data into spatial dfs
library(moments) # for kurtosis
library(tidygraph) # for converting into a network
library(igraph) # for network analysis
library(sp) # for converting to shapefile
library(raster) # for gridding
library(gstat) # for idw
library(vioplot) # for violin plots
library(h3jsr) # for h3 hexes
library(ggvoronoi) # for voronoi
library(units) # for manipulating geometry of voronoi
library(s2)
# library(h3) # for h3 idw
```

# Read in Primary Files
```{r}
# read in the data
buses.sf <- readRDS("./exports/buses_sf.rds")
lines.sf <- readRDS("./exports/lines_sf.rds")
```

# Buses

```{r}
library(jsonlite)
library(sf)
buses.h3 <- readRDS("./exports/buses_h3.rds")

# convert from a sf shapefile dataframe to regular df
buses.h3.df <- st_drop_geometry(buses.h3)

# drop the area columns from buses.h3
# buses.h3.df <- subset(buses.h3.df, select = -c(area))


buses.h3.json <- toJSON(buses.h3.df)

# export as csv and json
write(buses.h3.json, file="./exports/buses_h3.json")
# write.csv(buses.h3, "./exports/buses_h3.csv")
```

# Voronoi
```{r}
library(sf)
library(jsonlite)

# read in voronoi.sf
voronoi.sf <- readRDS("./exports/voronoi_sf.rds")

# drop the columns dev, weighted_voltage_n10_d2, lng, lat, area, voltage.rounded
voronoi.sf <- subset(voronoi.sf, select = -c(dev, weighted_voltage_n10_d2, lng, lat, area, voltage.rounded))

# convert into a geojson file
st_write(voronoi.sf, "./exports/voronoi.geo.json", driver = "GeoJSON")
```

# Heatmap
```{r}
library(jsonlite)
library(sf)
buses.idw.sf <- readRDS("./exports/buses_idw_sf_k100_n1.rds")
buses.idw.df <- st_drop_geometry(buses.idw.sf)

# rename long to longitude and lat to latitude
buses.idw.df <- buses.idw.df %>% rename(longitude = long, latitude = lat)
buses.idw.json <- toJSON(buses.idw.df)

# export as csv and json
write(buses.idw.json, file="./exports/contours.json")

# export as a geojson
# drop the columns lat, long
buses.idw.mini.sf <- subset(buses.idw.sf, select = -c(long, lat))

# convert into a geojson file
st_write(buses.idw.mini.sf, "./exports/contours.geo.json", driver = "GeoJSON")
```

# S2 Tiles
```{r}
library(jsonlite)
library(sf)
library(s2)
buses.s2 <- readRDS("./exports/buses_s2.rds")


# convert from a sf shapefile dataframe to regular df
buses.s2.df <- st_drop_geometry(buses.s2)
buses.s2.df$s2 <- as.character(buses.s2$s2)

# keep only resolution 16
buses.s2.df <- buses.s2.df %>% filter(res == 16)

# drop the area columns from buses.s2
# buses.s2.df <- subset(buses.s2.df, select = -c(count))
buses.s2.json <- toJSON(buses.s2.df)

# export as csv and json
write(buses.s2.json, file="./exports/buses_s2_r16.json")
# write.csv(buses.h3, "./exports/buses_s2.csv")
```

# H3 Tiles