---
title: "parse"
author: "Isaiah Lyons-Galante"
date: "2023-11-10"
output: html_document
---

# Load Libraries
```{r}
library(tidyverse) # for data reading and processing
library(jsonlite)
library(sf)
```

## Open Voltage DSS Files
```{r}
# read in all of the bus coordinates
buscoords1 <- read.table("./p13u_violations/p13uhs5_1247--p13udt7430/Buscoords.dss", header = FALSE, sep = " ")
buscoords2 <- read.table("./p13u_violations/p13uhs5_1247--p13udt27246/Buscoords.dss", header = FALSE, sep = " ")
buscoords3 <- read.table("./p13u_violations/p13uhs21_1247--p13udt10447/Buscoords.dss", header = FALSE, sep = " ")
buscoords4 <- read.table("./p13u_violations/p13uhs22_1247--p13udt4524/Buscoords.dss", header = FALSE, sep = " ")
buscoords5 <- read.table("./p13u_violations/p13uhs22_1247--p13udt26466/Buscoords.dss", header = FALSE, sep = " ")
buscoords6 <- read.table("./p13u_violations/p13uhs23_1247--p13udt28279/Buscoords.dss", header = FALSE, sep = " ")

# combine the buscoords with rbind
buscoords <- rbind(buscoords1, buscoords2, buscoords3, buscoords4, buscoords5, buscoords6)
colnames(buscoords) <- c("bus", "lng", "lat")
rm(buscoords1, buscoords2, buscoords3, buscoords4, buscoords5, buscoords6)

# read in the bus voltages
busvoltages <- read.csv("./p13u_violations/bus_voltages.csv", header = TRUE, sep = ",")

# replace zero voltages with the system mean
busvoltages$voltage[busvoltages$voltage == 0] <- mean(busvoltages$voltage)

hist(busvoltages$voltage)
# group the buses by bus name and take the mean voltage
busvoltages <- busvoltages %>% group_by(bus) %>% summarise(voltage = mean(voltage))

# merge the buscoords with the busvoltages by the bus name
buses.df <- merge(buscoords, busvoltages, by = "bus")
rm(buscoords, busvoltages)

# change the zero voltage values to 1
buses.df$voltage[buses.df$voltage == 0] <- 1

# create voltage deviation column
buses.df <- buses.df %>% mutate(dev = abs(voltage - 1))

# export buses.df into an RDS object in the exports folder
saveRDS(buses.df, "./exports/buses_df.rds")
```

## Open and Parse Lines DSS Files
```{r}
# read in all of the lines
linesdss1 <- read.table("./p13u_violations/p13uhs5_1247--p13udt7430/Lines.dss", header = FALSE, sep = "\n")
linesdss2 <- read.table("./p13u_violations/p13uhs5_1247--p13udt27246/Lines.dss", header = FALSE, sep = "\n")
linesdss3 <- read.table("./p13u_violations/p13uhs21_1247--p13udt10447/Lines.dss", header = FALSE, sep = "\n")
linesdss4 <- read.table("./p13u_violations/p13uhs22_1247--p13udt4524/Lines.dss", header = FALSE, sep = "\n")
linesdss5 <- read.table("./p13u_violations/p13uhs22_1247--p13udt26466/Lines.dss", header = FALSE, sep = "\n")
linesdss6 <- read.table("./p13u_violations/p13uhs23_1247--p13udt28279/Lines.dss", header = FALSE, sep = "\n")

# combine all lines with rbind
linesdss <- rbind(linesdss1, linesdss2, linesdss3, linesdss4, linesdss5, linesdss6)
rm(linesdss1, linesdss2, linesdss3, linesdss4, linesdss5, linesdss6)

# separate the character strings into columns by the spaces
lines.df <- linesdss %>% separate(V1, into = c("new", "line", "units", "length", "bus1", "bus2", "switch", "enabled", "phases", "linecode"), sep = " ")
rm(linesdss)

# remove any rows that contain any NAs
lines.df <- lines.df %>% drop_na()

# drop the columns new, length, units, switch, enabled, phases, linecode
lines.df <- lines.df %>% select(-new, -length, -units, -switch, -enabled, -phases, -linecode)

# remove the prefix "bus1=" and "bus2=" from the bus1 and bus2 columns
lines.df$bus1 <- gsub("bus1=", "", lines.df$bus1)
lines.df$bus2 <- gsub("bus2=", "", lines.df$bus2)

# remove the characters after the first "." in the columns bus1 and bus2
lines.df$bus1 <- gsub("\\..*", "", lines.df$bus1)
lines.df$bus2 <- gsub("\\..*", "", lines.df$bus2)

# ensure every bus in bus1 and bus2 is in buses.df and remove any that are not # 5 removed
lines.df <- lines.df %>% filter(bus1 %in% buses.df$bus) %>% filter(bus2 %in% buses.df$bus)

# remove any duplicate lines based on bus1 and bus2
lines.df <- lines.df %>% distinct(bus1, bus2, .keep_all = TRUE)

# export
saveRDS(lines.df, "./exports/lines_df.rds")
```

## Read in Transformers
```{r}
# read in all of the lines
txdss1 <- read.table("./p13u_violations/p13uhs5_1247--p13udt7430/Transformers.dss", header = FALSE, sep = "\n")
txdss2 <- read.table("./p13u_violations/p13uhs5_1247--p13udt27246/Transformers.dss", header = FALSE, sep = "\n")
txdss3 <- read.table("./p13u_violations/p13uhs21_1247--p13udt10447/Transformers.dss", header = FALSE, sep = "\n")
txdss4 <- read.table("./p13u_violations/p13uhs22_1247--p13udt4524/Transformers.dss", header = FALSE, sep = "\n")
txdss5 <- read.table("./p13u_violations/p13uhs22_1247--p13udt26466/Transformers.dss", header = FALSE, sep = "\n")
txdss6 <- read.table("./p13u_violations/p13uhs23_1247--p13udt28279/Transformers.dss", header = FALSE, sep = "\n")

# combine all lines with rbind
txdss <- rbind(txdss1, txdss2, txdss3, txdss4, txdss5, txdss6)
rm(txdss1, txdss2, txdss3, txdss4, txdss5, txdss6)

# separate the 2 winding from 3 winding transformers
tx.w2.dss <- txdss %>% filter(grepl("windings=2", V1))
tx.w3.dss <- txdss %>% filter(grepl("windings=3", V1))
rm(txdss)

# separate the character strings into columns by the spaces for each table of windings
tx.w2.df <- tx.w2.dss %>% separate(V1, into = c(
  "New",
  "Transformer",
  "phases",
  "windings",
  "loadloss",
  "Noloadloss",
  "normhkva",
  "wdg1",
  "conn1",
  "Kv1",
  "kva1",
  "EmergHKVA1",
  "r1",
  "bus1",
  "wdg2",
  "conn2",
  "Kv2",
  "kva2",
  "EmergHKVA2",
  "r2",
  "bus2",
  "XHL"
  ), sep = " ")

tx.w3.df <- tx.w3.dss %>% separate(V1, into = c(
  "New",
  "Transformer",
  "phases",
  "windings",
  "loadloss",
  "Noloadloss",
  "normhkva",
  "wdg1",
  "conn1",
  "bus1",
  "Kv1",
  "kva1",
  "EmergHKVA1",
  "r1",
  "wdg2",
  "conn2",
  "bus2",
  "Kv2",
  "kva2",
  "EmergHKVA2",
  "r2",
  "wdg3",
  "conn3",
  "bus3",
  "Kv3",
  "kva3",
  "EmergHKVA3",
  "r3",
  "XHL",
  "XLT",
  "XHT"
  ), sep = " ")

rm(tx.w2.dss, tx.w3.dss)

# Remove extra columns
tx.w3.df <- tx.w3.df %>% select(-New,-phases,-loadloss,-Noloadloss,-normhkva,-wdg1,-conn1,-Kv1,-kva1,-EmergHKVA1,-r1,-wdg2,-conn2,-Kv2,-kva2,-EmergHKVA2,-r2,-wdg3,-conn3,-Kv3,-kva3,-EmergHKVA3,-r3,-XHL,-XLT,-XHT)
tx.w2.df <- tx.w2.df %>% select(-New,-phases,-loadloss,-Noloadloss,-normhkva,-wdg1,-conn1,-Kv1,-kva1,-EmergHKVA1,-r1,-wdg2,-conn2,-Kv2,-kva2,-EmergHKVA2,-r2,-XHL)
tx.w2.df$bus3 <- NA

# Combine into a single df
tx.df <- rbind(tx.w2.df, tx.w3.df)
rm(tx.w2.df, tx.w3.df)

# filter for 3 winding transformers
tx.w3.df <- tx.df %>% filter(windings == 3)
tx.w3.df <- tx.w3.df %>% filter(bus2 != bus3) 
# always equal >> drop the third bus
rm(tx.w3.df)

# drop the bus3 and windings column
tx.df <- tx.df %>% select(-bus3, -windings)
tx.df <- tx.df %>% rename(line = Transformer)

# Remove the prefix "bus=" from the bus names
tx.df$bus1 <- gsub("bus=", "", tx.df$bus1)
tx.df$bus2 <- gsub("bus=", "", tx.df$bus2)

# Remove everything after the period in the bus names
tx.df$bus1 <- gsub("\\..*", "", tx.df$bus1)
tx.df$bus2 <- gsub("\\..*", "", tx.df$bus2)

# export the df as RDS
saveRDS(tx.df, "./exports/tx_df.rds")
```

# Convert to Spatial Data & Visualize

## Convert Buses to Spatial Data Frames
```{r}
library(sf) # for converting data into spatial dfs
# read in buses and lines.df
buses.df <- readRDS("./exports/buses_df.rds")

# convert buses.df to a sf object
buses.sf <- st_as_sf(buses.df, coords = c("lng", "lat"), crs = 4326)

# check of any of the buses share the same geometry -- none do
buses.sf %>% group_by(geometry) %>% summarise(n = n()) %>% filter(n > 1)

# export buses sf as RDS
saveRDS(buses.sf, "./exports/buses_sf.rds")
```

## Convert Lines and Transformers to Spatial Data Frames
```{r}
# read in lines and transformers
lines.df <- readRDS("./exports/lines_df.rds")
tx.df <- readRDS("./exports/tx_df.rds")

# merge into one single df
lines.df <- rbind(lines.df, tx.df)
rm(tx.df)

# merge the lines.df with the buses.df by bus1
lines.df <- merge(lines.df, buses.df, by.x = "bus1", by.y = "bus")
# drop voltage, rename lng to lng1, and lat to lat1
lines.df <- lines.df %>% select(-voltage) %>% rename(lng1 = lng, lat1 = lat)

# merge the lines.df with the buses.df by bus2
lines.df <- merge(lines.df, buses.df, by.x = "bus2", by.y = "bus")
# drop voltage, rename lng to lng2, and lat to lat2
lines.df <- lines.df %>% select(-voltage) %>% rename(lng2 = lng, lat2 = lat)

# rename bus1 to from and bus2 to to
lines.df <- lines.df %>% rename(from = bus1, to = bus2)

linestrings <- apply(lines.df, 1, function(x) 
  {
    v <- as.numeric(x[c("lng1","lng2","lat1","lat2")])
    m <- matrix(v, nrow = 2)
    return(st_sfc(st_linestring(m), crs = 4326))
  }
)

##############################################
linestrings = Reduce(c, linestrings)
lines.df$geometry <- linestrings

# clean up
rm(linestrings)
lines.df <- lines.df %>% select(-lat1, -lat2, -lng1, -lng2)

# convert lines.df to a sf object
lines.sf <- st_as_sf(lines.df, crs = 4326)

# check if any two lines share the same geometry -- 19 do, whatever
# lines.sf.2 <- lines.sf %>% distinct(geometry, .keep_all = TRUE)
 
# export files
saveRDS(lines.sf, "./exports/lines_sf.rds")
```

## Create a Bounding Box around Lines
```{r}
# import lines
lines.sf <- readRDS("./exports/lines_sf.rds")

# merge the lines spatially into a single geometry
lines.all <- st_union(lines.sf)

# create a 50m buffer around lines.all
lines.buffer <- st_buffer(lines.all, endCapStyle = "SQUARE", dist = 100, max_cells = 10000)

# visualize the line buffer
plot(lines.buffer)

# export the line buffer to RDS
saveRDS(lines.buffer, "./exports/lines_buffer.rds")
```

## Visualize the Lines and Buses
```{r}
# plot it
ggmap(map) +
  geom_sf(
    data = lines.sf, 
    color="yellow", 
    alpha = 1.0, 
    inherit.aes = FALSE
  ) +
  geom_sf(
    data = buses.sf, 
    # aes(color = voltage, cex = dev),
    alpha = 0.5,
    inherit.aes = FALSE,
    cex = 0.7,
    color = "darkgreen"
  ) +
  scale_size_continuous(
    range = c(0, 3),
    limits = c(0, 0.05)
  ) +
  scale_color_gradient2(
    low = "darkblue",
    mid = "white",
    high = "darkred",
    midpoint = 1,
    limits = c(0.95, 1.05),
    space = "Lab",
    guide = "colourbar",
    aesthetics = "color",
    oob = scales::squish
  ) +
  theme(
    legend.position = c(0.96, 0.15),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    text = element_text(family = "Serif", size = 18)
  ) +
  coord_sf(xlim = c(left, right), ylim = c(bottom, top)) +
  guides(size = FALSE)
```

## Open Load DSS Files
```{r}
# read in all of the load coordinates
loads1 <- read.table("./p13u_violations/p13uhs5_1247--p13udt7430/Loads.dss", header = FALSE, sep = " ")
loads2 <- read.table("./p13u_violations/p13uhs5_1247--p13udt27246/Loads.dss", header = FALSE, sep = " ")
loads3 <- read.table("./p13u_violations/p13uhs21_1247--p13udt10447/Loads.dss", header = FALSE, sep = " ")
loads4 <- read.table("./p13u_violations/p13uhs22_1247--p13udt4524/Loads.dss", header = FALSE, sep = " ")
loads5 <- read.table("./p13u_violations/p13uhs22_1247--p13udt26466/Loads.dss", header = FALSE, sep = " ")
loads6 <- read.table("./p13u_violations/p13uhs23_1247--p13udt28279/Loads.dss", header = FALSE, sep = " ")

# combine the buscoords with rbind
loads.df <- rbind(loads1, loads2, loads3, loads4, loads5, loads6)
rm(loads1, loads2, loads3, loads4, loads5, loads6)

# remove any rows that contain any NAs
loads.df <- loads.df %>% drop_na() # none drop

# drop uninteresting columns
loads.df <- loads.df %>% select(-V1, -V3, -V6, -V7, -V8)

# rename interesting columns
loads.df <- loads.df %>% rename(
    name = V2,
    bus1 = V4,
    kV = V5
    ################################################
    ########################################################################
    ################################################
    ################################################
    ################################################
    ################################################
)

# remove the prefix "bus1=" and "bus2=" from the bus1 and bus2 columns
loads.df$bus1 <- gsub("bus1=", "", loads.df$bus1)
loads.df$bus2 <- gsub("bus2=", "", loads.df$bus2)

# remove the characters after the first "." in the columns bus1 and bus2
loads.df$bus1 <- gsub("\\..*", "", loads.df$bus1)
loads.df$bus2 <- gsub("\\..*", "", loads.df$bus2)

# ensure every bus in bus1 and bus2 is in buses.df and remove any that are not # 5 removed
loads.df <- loads.df %>% filter(bus1 %in% buses.df$bus) %>% filter(bus2 %in% buses.df$bus)

# remove any duplicate loads based on bus1 and bus2
loads.df <- loads.df %>% distinct(bus1, bus2, .keep_all = TRUE)

# export
saveRDS(loads.df, "./exports/loads_df.rds")```