---
title: "conversions"
author: "Isaiah Lyons-Galante"
date: "2023-11-09"
output: html_document
---

# Load Libraries
```{r}
library(tidyverse) # for data reading and processing
library(jsonlite)
library(sf)
```

# Buses
```{r}
# read in data
buses.sf <- readRDS("./exports/buses_sf.rds")

# look at bus columns
colnames(buses.sf)

# drop the columns dev, weighted_voltage_n10_d2, weighted_voltage_n3_d2
buses.sf <- subset(buses.sf, select = -c(dev, weighted_voltage_n10_d2, weighted_voltage_n3_d2))
# change column bus to name
buses.sf <- buses.sf %>% rename(name = bus)

# convert voltage 0s to 1s
buses.sf$voltage[buses.sf$voltage == 0] <- 1

# export as geojson
st_write(buses.sf, "./exports/buses.geo.json", driver = "GeoJSON")
```

# Lines
```{r}
# read in data
lines.sf <- readRDS("./exports/lines_sf.rds")

# look at line columns
colnames(lines.sf)

# convert "to" to "bus1" and "from" to "bus2" and "line" to "name"
lines.sf <- lines.sf %>% rename(bus1 = to, bus2 = from, name = line)

# drop the columns dev.x and dev.y
lines.sf <- subset(lines.sf, select = -c(dev.x, dev.y))


# add column current with random values between 0 and 1
set.seed(44)
lines.sf$current <- runif(nrow(lines.sf), min = 0, max = 1)

# export as geojson
st_write(lines.sf, "./exports/lines.geo.json", driver = "GeoJSON")
```

# H3
```{r}

buses.h3 <- readRDS("./exports/buses_h3.rds")

# convert from a sf shapefile dataframe to regular df
buses.h3.df <- st_drop_geometry(buses.h3)

# drop the area columns from buses.h3
# buses.h3.df <- subset(buses.h3.df, select = -c(area))


buses.h3.json <- toJSON(buses.h3.df)

# export as csv and json
write(buses.h3.json, file="./exports/buses_h3.json")
# write.csv(buses.h3, "./exports/buses_h3.csv")
```

# Voronoi
```{r}
library(sf)
library(jsonlite)

# read in voronoi.sf
voronoi.sf <- readRDS("./exports/voronoi_sf.rds")

# drop the columns dev, weighted_voltage_n10_d2, lng, lat, area, voltage.rounded
voronoi.sf <- subset(voronoi.sf, select = -c(dev, weighted_voltage_n10_d2, lng, lat, area, voltage.rounded))

# convert into a geojson file
st_write(voronoi.sf, "./exports/voronoi.geo.json", driver = "GeoJSON")
```

# Heatmap
```{r}
library(jsonlite)
library(sf)
buses.idw.sf <- readRDS("./exports/buses_idw_sf_k100_n1.rds")
buses.idw.df <- st_drop_geometry(buses.idw.sf)

# rename long to longitude and lat to latitude
buses.idw.df <- buses.idw.df %>% rename(longitude = long, latitude = lat)
buses.idw.json <- toJSON(buses.idw.df)

# export as csv and json
write(buses.idw.json, file="./exports/contours.json")

# export as a geojson
# drop the columns lat, long
buses.idw.mini.sf <- subset(buses.idw.sf, select = -c(long, lat))

# convert into a geojson file
st_write(buses.idw.mini.sf, "./exports/contours.geo.json", driver = "GeoJSON")
```

# S2 Tiles
```{r}
library(jsonlite)
library(sf)
library(s2)
buses.s2 <- readRDS("./exports/buses_s2.rds")


# convert from a sf shapefile dataframe to regular df
buses.s2.df <- st_drop_geometry(buses.s2)
buses.s2.df$s2 <- as.character(buses.s2$s2)

# keep only resolution 16
buses.s2.df <- buses.s2.df %>% filter(res == 16)

# drop the area columns from buses.s2
# buses.s2.df <- subset(buses.s2.df, select = -c(count))
buses.s2.json <- toJSON(buses.s2.df)

# export as csv and json
write(buses.s2.json, file="./exports/buses_s2_r16.json")
# write.csv(buses.h3, "./exports/buses_s2.csv")
```

# Charging Stations
```{r}
buses.sf <- readRDS("./exports/buses_sf.rds")

# keep only every 250th line
stations.sf <- buses.sf %>% subset(voltage < 0.99)
nrow(stations.sf)

# convert column names & drop extra columns
stations.sf <- stations.sf %>% 
    rename(name = bus) %>% 
    subset(select = -c(dev, voltage, weighted_voltage_n10_d2, weighted_voltage_n3_d2))


stations.sf$rating <- 150
stations.sf[1:10,]$rating <- 300
stations.sf[40:76,]$rating <- 70

# export as json
st_write(stations.sf, "./exports/evstations.geo.json", driver = "GeoJSON")
```