# Contours

## Load General Libraries
```{r}
library(tidyverse)
library(sf)
library(ggmap)
```

## Read in Data
```{r}
# read in RDS 
# lines.sf <- readRDS("10x/variables/lines_sf.rds")
buses.sf <- readRDS("10x/variables/buses_sf.rds")
map <- readRDS("10x/variables/map_stadia_z14.rds")

# get the bounding box of map
left <- attr(map, "bb")$ll.lon
right <- attr(map, "bb")$ur.lon
bottom <- attr(map, "bb")$ll.lat
top <- attr(map, "bb")$ur.lat
```

## Load Contour Map Libraries
```{r}
library(terra)
library(gstat)
```

## Create Contours
```{r}
# load in lines buffer
buses.sf <- readRDS("10x/variables/buses_sf.rds")
buses.buffer.vec <- readRDS("10x/variables/buses_buffer_1000m_vec.rds")

# get the extent of buses.buffer.vec
ext <- ext(buses.buffer.vec)
# create a grid of the same extent
grd <- rast(ext, res=0.0001)

# convert buses.sf to buses.df
buses.df <- buses.sf %>% st_drop_geometry()
# drop nas from any column
buses.df <- na.omit(buses.df)
# rename lng and lat to x and y
names(buses.df) <- c("name", "voltage", "x", "y")
# glimpse(buses.df)

neighbors <- 1000
# define interpolation model
mg <- gstat(
  id = "idw", 
  formula = voltage~1, 
  locations = ~x+y, 
  data=buses.df, 
  nmax=neighbors, 
  set=list(idp = 2)
)
######################
contour <- interpolate(grd, mg, debug.level=0, index=1)
saveRDS(contour, "10x/variables/contour_n10_rast.rds")
######################

# clear out extra variables not needed later
rm(buses.sf, buses.df, buses.buffer.vec, ext, grd, neighbors, mg)
```

## Prepare Contour for Plotting by Masking
```{r}  
# read in data
contour <- readRDS("10x/variables/contour_n100_rast.rds")
buses.buffer.vec <- readRDS("10x/variables/buses_buffer_1000m_vec.rds")
# merge all the polygons into a single one
buses.buffer.vec <- terra::union(buses.buffer.vec)
buses

buses.buffer.vec.simple <- terra::simplifyGeom(buses.buffer.vec, tolerance = 0.1)

buses.buffer.vec
buses.buffer.vec.simple
# mask
contour.mask <- mask(contour, buses.buffer.vec)

# convert to data.frame
contour.df <- as.data.frame(contour.mask, xy=TRUE)

# rename idw.pred to voltage
contour.df <- contour.df %>% rename(voltage = idw.pred)

# remove rows with NA in any column
# contour.df <- na.omit(contour.df) # removes none

# export df 
saveRDS(contour.df, "10x/variables/contour_mask_n10_df.rds")
# glimpse(contour.df)

rm(contour.mask, contour.df, contour, buses.buffer.vec)
```
Rows: 3,553,912
Columns: 3
$ x        <dbl> -122.3447, -122.3446, -122.3445, -122.3444, -122.3443, -122.3…
$ y        <dbl> 37.90743, 37.90743, 37.90743, 37.90743, 37.90743, 37.90743, 3…
$ voltage <dbl> 0.9800596, 0.9800594, 0.9800592, 0.9800590, 0.9800588, 0.9800…

## Plot Contours
```{r}
# import map
map <- readRDS("10x/variables/map_stadia_z14.rds")
contour.df <- readRDS("10x/variables/contour_mask_n10_df.rds")

# glimpse(contour.df)
# plot it
contour_plot <- ggmap(map) +
  geom_raster(
    data = contour.df,
    aes(x=x, y=y, fill = voltage),
    alpha = 1.0,
    inherit.aes = FALSE
  ) +
#   geom_sf(
#     data = lines.sf, 
#     color="black", 
#     alpha = 0.05, 
#     inherit.aes = FALSE
#   ) +
  scale_fill_gradient2(
    low = "darkblue",
    mid = "white",
    high = "darkred",
    midpoint = 1,
    limits = c(0.95, 1.05),
    space = "Lab",
    guide = "colourbar",
    aesthetics = "fill",
    oob = scales::squish
  ) +
  theme(
    legend.position = c(0.96, 0.15),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank(),
    text = element_text(family = "Serif", size = 18)
  ) +
  coord_sf(xlim = c(left, right), ylim = c(bottom, top)
)

ggsave(
  filename = "10x/figures/contour_plot_mask_n10_1000m_filled.png", 
  contour_plot,
  width = 6480,
  height = 6480,
  dpi = 300,
  units = "px",
  device = "png",
  limitsize = FALSE
)

rm(contour_plot, contour.df)
```