---
title: "parse"
author: "Isaiah Lyons-Galante"
date: "2023-11-10"
output: html_document
---

# Load Libraries
```{r}
library(tidyverse) # for data reading and processing
library(jsonlite)
library(sf)
```

## Open Voltage DSS Files
```{r}
# read in all of the bus coordinates
buscoords1 <- read.table("./p13u_violations/p13uhs5_1247--p13udt7430/Buscoords.dss", header = FALSE, sep = " ")
buscoords2 <- read.table("./p13u_violations/p13uhs5_1247--p13udt27246/Buscoords.dss", header = FALSE, sep = " ")
buscoords3 <- read.table("./p13u_violations/p13uhs21_1247--p13udt10447/Buscoords.dss", header = FALSE, sep = " ")
buscoords4 <- read.table("./p13u_violations/p13uhs22_1247--p13udt4524/Buscoords.dss", header = FALSE, sep = " ")
buscoords5 <- read.table("./p13u_violations/p13uhs22_1247--p13udt26466/Buscoords.dss", header = FALSE, sep = " ")
buscoords6 <- read.table("./p13u_violations/p13uhs23_1247--p13udt28279/Buscoords.dss", header = FALSE, sep = " ")

# combine the buscoords with rbind
buscoords <- rbind(buscoords1, buscoords2, buscoords3, buscoords4, buscoords5, buscoords6)
colnames(buscoords) <- c("bus", "lng", "lat")
rm(buscoords1, buscoords2, buscoords3, buscoords4, buscoords5, buscoords6)

# read in the bus voltages
busvoltages <- read.csv("./p13u_violations/bus_voltages.csv", header = TRUE, sep = ",")

# replace zero voltages with the system mean
busvoltages$voltage[busvoltages$voltage == 0] <- mean(busvoltages$voltage)

hist(busvoltages$voltage)
# group the buses by bus name and take the mean voltage
busvoltages <- busvoltages %>% group_by(bus) %>% summarise(voltage = mean(voltage))

# merge the buscoords with the busvoltages by the bus name
buses.df <- merge(buscoords, busvoltages, by = "bus")
rm(buscoords, busvoltages)

# change the zero voltage values to 1
buses.df$voltage[buses.df$voltage == 0] <- 1

# create voltage deviation column
buses.df <- buses.df %>% mutate(dev = abs(voltage - 1))

# export buses.df into an RDS object in the exports folder
saveRDS(buses.df, "./exports/buses_df.rds")
```

## Open and Parse Lines DSS Files
```{r}
# read in all of the lines
linesdss1 <- read.table("./p13u_violations/p13uhs5_1247--p13udt7430/Lines.dss", header = FALSE, sep = "\n")
linesdss2 <- read.table("./p13u_violations/p13uhs5_1247--p13udt27246/Lines.dss", header = FALSE, sep = "\n")
linesdss3 <- read.table("./p13u_violations/p13uhs21_1247--p13udt10447/Lines.dss", header = FALSE, sep = "\n")
linesdss4 <- read.table("./p13u_violations/p13uhs22_1247--p13udt4524/Lines.dss", header = FALSE, sep = "\n")
linesdss5 <- read.table("./p13u_violations/p13uhs22_1247--p13udt26466/Lines.dss", header = FALSE, sep = "\n")
linesdss6 <- read.table("./p13u_violations/p13uhs23_1247--p13udt28279/Lines.dss", header = FALSE, sep = "\n")

# combine all lines with rbind
linesdss <- rbind(linesdss1, linesdss2, linesdss3, linesdss4, linesdss5, linesdss6)
rm(linesdss1, linesdss2, linesdss3, linesdss4, linesdss5, linesdss6)

# separate the character strings into columns by the spaces
lines.df <- linesdss %>% separate(V1, into = c("new", "line", "units", "length", "bus1", "bus2", "switch", "enabled", "phases", "linecode"), sep = " ")
rm(linesdss)

# remove any rows that contain any NAs
lines.df <- lines.df %>% drop_na()

# drop the columns new, length, units, switch, enabled, phases, linecode
lines.df <- lines.df %>% select(-new, -length, -units, -switch, -enabled, -phases, -linecode)

# remove the prefix "bus1=" and "bus2=" from the bus1 and bus2 columns
lines.df$bus1 <- gsub("bus1=", "", lines.df$bus1)
lines.df$bus2 <- gsub("bus2=", "", lines.df$bus2)

# remove the characters after the first "." in the columns bus1 and bus2
lines.df$bus1 <- gsub("\\..*", "", lines.df$bus1)
lines.df$bus2 <- gsub("\\..*", "", lines.df$bus2)

# ensure every bus in bus1 and bus2 is in buses.df and remove any that are not # 5 removed
lines.df <- lines.df %>% filter(bus1 %in% buses.df$bus) %>% filter(bus2 %in% buses.df$bus)

# remove any duplicate lines based on bus1 and bus2
lines.df <- lines.df %>% distinct(bus1, bus2, .keep_all = TRUE)

# export
saveRDS(lines.df, "./exports/lines_df.rds")
```

## Read in Transformers
```{r}
# read in all of the lines
txdss1 <- read.table("./p13u_violations/p13uhs5_1247--p13udt7430/Transformers.dss", header = FALSE, sep = "\n")
txdss2 <- read.table("./p13u_violations/p13uhs5_1247--p13udt27246/Transformers.dss", header = FALSE, sep = "\n")
txdss3 <- read.table("./p13u_violations/p13uhs21_1247--p13udt10447/Transformers.dss", header = FALSE, sep = "\n")
txdss4 <- read.table("./p13u_violations/p13uhs22_1247--p13udt4524/Transformers.dss", header = FALSE, sep = "\n")
txdss5 <- read.table("./p13u_violations/p13uhs22_1247--p13udt26466/Transformers.dss", header = FALSE, sep = "\n")
txdss6 <- read.table("./p13u_violations/p13uhs23_1247--p13udt28279/Transformers.dss", header = FALSE, sep = "\n")

# combine all lines with rbind
txdss <- rbind(txdss1, txdss2, txdss3, txdss4, txdss5, txdss6)
rm(txdss1, txdss2, txdss3, txdss4, txdss5, txdss6)

# separate the 2 winding from 3 winding transformers
tx.w2.dss <- txdss %>% filter(grepl("windings=2", V1))
tx.w3.dss <- txdss %>% filter(grepl("windings=3", V1))
rm(txdss)

# separate the character strings into columns by the spaces for each table of windings
tx.w2.df <- tx.w2.dss %>% separate(V1, into = c(
  "New",
  "Transformer",
  "phases",
  "windings",
  "loadloss",
  "Noloadloss",
  "normhkva",
  "wdg1",
  "conn1",
  "Kv1",
  "kva1",
  "EmergHKVA1",
  "r1",
  "bus1",
  "wdg2",
  "conn2",
  "Kv2",
  "kva2",
  "EmergHKVA2",
  "r2",
  "bus2",
  "XHL"
  ), sep = " ")

tx.w3.df <- tx.w3.dss %>% separate(V1, into = c(
  "New",
  "Transformer",
  "phases",
  "windings",
  "loadloss",
  "Noloadloss",
  "normhkva",
  "wdg1",
  "conn1",
  "bus1",
  "Kv1",
  "kva1",
  "EmergHKVA1",
  "r1",
  "wdg2",
  "conn2",
  "bus2",
  "Kv2",
  "kva2",
  "EmergHKVA2",
  "r2",
  "wdg3",
  "conn3",
  "bus3",
  "Kv3",
  "kva3",
  "EmergHKVA3",
  "r3",
  "XHL",
  "XLT",
  "XHT"
  ), sep = " ")

rm(tx.w2.dss, tx.w3.dss)

# # Remove extra columns
# tx.w3.df <- tx.w3.df %>% select(
#   -New,
#   -phases,
#   -loadloss,
#   -Noloadloss,
#   -normhkva,
#   -wdg1,
#   -conn1,
#   -Kv1,
#   -kva1,
#   -EmergHKVA1,
#   -r1,
#   -wdg2,
#   -conn2,
#   -Kv2,
#   -kva2,
#   -EmergHKVA2,
#   -r2,
#   -wdg3,
#   -conn3,
#   -Kv3,
#   -kva3,
#   -EmergHKVA3,
#   -r3,
#   -XHL,
#   -XLT,
#   -XHT
# )
# tx.w2.df <- tx.w2.df %>% select(
#   -New,
#   -phases,
#   -loadloss,
#   -Noloadloss,
#   -normhkva,
#   -wdg1,
#   -conn1,
#   -Kv1,
#   -kva1,
#   -EmergHKVA1,
#   -r1,
#   -wdg2,
#   -conn2,
#   -Kv2,
#   -kva2,
#   -EmergHKVA2,
#   -r2,
#   -XHL
# )

# Remove extra columns
tx.w3.df <- tx.w3.df %>% select(
  -New,
  -wdg3,
  -conn3,
  -Kv3,
  -kva3,
  -EmergHKVA3,
  -r3,
  -XLT,
  -XHT
)
tx.w2.df <- tx.w2.df %>% select(
  -New
)
tx.w2.df$bus3 <- NA

# Combine into a single df
tx.df <- rbind(tx.w2.df, tx.w3.df)
rm(tx.w2.df, tx.w3.df)

# drop the bus3 and windings column
tx.df <- tx.df %>% rename(name = Transformer)


# parse the rest of the columns
tx.df$phases <- gsub("phases=", "", tx.df$phases)
tx.df$windings <- gsub("windings=", "", tx.df$windings)
tx.df$loadloss <- gsub("%loadloss=", "", tx.df$loadloss)
tx.df$Noloadloss <- gsub("%Noloadloss=", "", tx.df$Noloadloss)
tx.df$normhkva <- gsub("normhkva=", "", tx.df$normhkva)
tx.df$wdg1 <- gsub("wdg=", "", tx.df$wdg1)
tx.df$conn1 <- gsub("conn=", "", tx.df$conn1)
tx.df$Kv1 <- gsub("Kv=", "", tx.df$Kv1)
tx.df$kva1 <- gsub("kva=", "", tx.df$kva1)
tx.df$EmergHKVA1 <- gsub("EmergHKVA=", "", tx.df$EmergHKVA1)
tx.df$r1 <- gsub("%R=", "", tx.df$r1)
tx.df$bus1 <- gsub("bus=", "", tx.df$bus1)
tx.df$wdg2 <- gsub("wdg=", "", tx.df$wdg2)
tx.df$conn2 <- gsub("conn=", "", tx.df$conn2)
tx.df$Kv2 <- gsub("Kv=", "", tx.df$Kv2)
tx.df$kva2 <- gsub("kva=", "", tx.df$kva2)
tx.df$EmergHKVA2 <- gsub("EmergHKVA=", "", tx.df$EmergHKVA2)
tx.df$r2 <- gsub("%R=", "", tx.df$r2)
tx.df$bus2 <- gsub("bus=", "", tx.df$bus2)
tx.df$XHL <- gsub("XHL=", "", tx.df$XHL)
tx.df$bus3 <- gsub("bus=", "", tx.df$bus3)

# Remove everything after the period in the bus names
tx.df$bus1 <- gsub("\\..*", "", tx.df$bus1)
tx.df$bus2 <- gsub("\\..*", "", tx.df$bus2)
tx.df$bus3 <- gsub("\\..*", "", tx.df$bus3)

# export the df as RDS
saveRDS(tx.df, "./exports/tx_only_df.rds")
```

## Open Load DSS Files
```{r}
# read in all of the load coordinates
loads1 <- read.table("./p13u_violations/p13uhs5_1247--p13udt7430/Loads.dss", header = FALSE, sep = " ")
loads2 <- read.table("./p13u_violations/p13uhs5_1247--p13udt27246/Loads.dss", header = FALSE, sep = " ")
loads3 <- read.table("./p13u_violations/p13uhs21_1247--p13udt10447/Loads.dss", header = FALSE, sep = " ")
loads4 <- read.table("./p13u_violations/p13uhs22_1247--p13udt4524/Loads.dss", header = FALSE, sep = " ")
loads5 <- read.table("./p13u_violations/p13uhs22_1247--p13udt26466/Loads.dss", header = FALSE, sep = " ")
loads6 <- read.table("./p13u_violations/p13uhs23_1247--p13udt28279/Loads.dss", header = FALSE, sep = " ")

# combine the buscoords with rbind
loads.df <- rbind(loads1, loads2, loads3, loads4, loads5, loads6)
rm(loads1, loads2, loads3, loads4, loads5, loads6)

# remove any rows that contain any NAs
loads.df <- loads.df %>% drop_na() # none drop

# drop uninteresting columns
loads.df <- loads.df %>% select(-V1, -V3, -V6, -V7, -V8)

# rename interesting columns
loads.df <- loads.df %>% rename(
    name = V2,
    bus1 = V4,
    kV = V5,
    kW = V9,
    kvar = V10,
    phases = V11,
    yearly = V12
)

# remove the prefix "bus1=" from the bus1 column
loads.df$bus1 <- gsub("bus1=", "", loads.df$bus1)
loads.df$kV <- gsub("kV=", "", loads.df$kV)
loads.df$kW <- gsub("kW=", "", loads.df$kW)
loads.df$kvar <- gsub("kvar=", "", loads.df$kvar)
loads.df$phases <- gsub("Phases=", "", loads.df$phases)
loads.df$yearly <- gsub("yearly=", "", loads.df$yearly)

# remove the characters after the first "." in the columns bus1 and bus2
loads.df$bus1 <- gsub("\\..*", "", loads.df$bus1)

# ensure every bus in bus1 and bus2 is in buses.df and remove any that are not # 5 removed
buses.df <- readRDS("./exports/buses_df.rds")
loads.df <- loads.df %>% filter(bus1 %in% buses.df$bus)

# remove any duplicate loads based on bus1
# nevermind, this cuts it down in half
# loads.df <- loads.df %>% distinct(bus1, .keep_all = TRUE)

# export
saveRDS(loads.df, "./exports/loads_df.rds")
```

## Storage
```{r}
# read in all of the load coordinates
storage1 <- read.table("./p13u_violations/p13uhs5_1247--p13udt7430/Storage.dss", header = FALSE, sep = " ")
storage2 <- read.table("./p13u_violations/p13uhs5_1247--p13udt27246/Storage.dss", header = FALSE, sep = " ")
storage3 <- read.table("./p13u_violations/p13uhs21_1247--p13udt10447/Storage.dss", header = FALSE, sep = " ")
storage4 <- read.table("./p13u_violations/p13uhs22_1247--p13udt4524/Storage.dss", header = FALSE, sep = " ")
storage5 <- read.table("./p13u_violations/p13uhs22_1247--p13udt26466/Storage.dss", header = FALSE, sep = " ")
storage6 <- read.table("./p13u_violations/p13uhs23_1247--p13udt28279/Storage.dss", header = FALSE, sep = " ")

# combine the buscoords with rbind
storage.df <- rbind(storage1, storage2, storage3, storage4, storage5, storage6)
rm(storage1, storage2, storage3, storage4, storage5, storage6)

# remove any rows that contain any NAs
storage.df <- storage.df %>% drop_na() # none drop

# drop uninteresting columns
storage.df <- storage.df %>% select(-V1)

# rename interesting columns
storage.df <- storage.df %>% rename(
    name = V2,
    phases = V3,
    bus1 = V4,
    kV = V5,
    kVA = V6,
    kWRated = V7,
    kWhRated = V8,
    kWhStored = V9,
    State = V10,
    PercentEffCharge = V11,
    PercentEffDischarge = V12
)

# remove the prefix "bus1=" from the bus1 column
storage.df$phases <- gsub("phases=", "", storage.df$phases)
storage.df$bus1 <- gsub("bus1=", "", storage.df$bus1)
storage.df$kV <- gsub("kV=", "", storage.df$kV)
storage.df$kVA <- gsub("kVA=", "", storage.df$kVA)
storage.df$kWRated <- gsub("kWRated=", "", storage.df$kWRated)
storage.df$kWhRated <- gsub("kWhRated=", "", storage.df$kWhRated)
storage.df$kWhStored <- gsub("kWhStored=", "", storage.df$kWhStored)
storage.df$State <- gsub("State=", "", storage.df$State)
storage.df$PercentEffCharge <- gsub("PercentEffCharge=", "", storage.df$PercentEffCharge)
storage.df$PercentEffDischarge <- gsub("PercentEffDischarge=", "", storage.df$PercentEffDischarge)

# remove the characters after the first "." in the columns bus1 and bus2
storage.df$bus1 <- gsub("\\..*", "", storage.df$bus1)

# ensure every bus in bus1 and bus2 is in buses.df and remove any that are not # 5 removed
buses.df <- readRDS("./exports/buses_df.rds")
storage.df <- storage.df %>% filter(bus1 %in% buses.df$bus) # none removed

# remove any duplicate storage based on bus1
# nevermind, this removes 3 of them
# storage.df <- storage.df %>% distinct(bus1, .keep_all = TRUE)

# export
saveRDS(storage.df, "./exports/storage_df.rds")
```

## PV Systems
```{r}
# read in all of the load coordinates
pv1 <- read.table("./p13u_violations/p13uhs5_1247--p13udt7430/PVSystems.dss", header = FALSE, sep = " ", fill = TRUE)
pv2 <- read.table("./p13u_violations/p13uhs5_1247--p13udt27246/PVSystems.dss", header = FALSE, sep = " ", fill = TRUE)
pv3 <- read.table("./p13u_violations/p13uhs21_1247--p13udt10447/PVSystems.dss", header = FALSE, sep = " ", fill = TRUE)
pv4 <- read.table("./p13u_violations/p13uhs22_1247--p13udt4524/PVSystems.dss", header = FALSE, sep = " ", fill = TRUE)
pv5 <- read.table("./p13u_violations/p13uhs22_1247--p13udt26466/PVSystems.dss", header = FALSE, sep = " ", fill = TRUE)
pv6 <- read.table("./p13u_violations/p13uhs23_1247--p13udt28279/PVSystems.dss", header = FALSE, sep = " ", fill = TRUE)

# combine the buscoords with rbind
pv.df <- rbind(pv1, pv2, pv3, pv4, pv5, pv6)
rm(pv1, pv2, pv3, pv4, pv5, pv6)

# remove any rows that contain any NAs
pv.df <- pv.df %>% drop_na() # none drop

# remove any rows where V13 doesn't begin with "yearly="
pv.df <- pv.df %>% filter(grepl("yearly=", V13)) # drops 4

# drop uninteresting columns
pv.df <- pv.df %>% select(-V1, -V10, -V12, -V13)

# print the values from the first row
pv.df[1,]


# rename interesting columns
pv.df <- pv.df %>% rename(
    name = V2,
    bus1 = V3,
    phases = V4,
    kV = V5,
    kVA = V6,
    pmpp = V7,
    percentCutout = V8,
    percentCutin = V9,
    pf = V11
)

# remove the prefix "bus1=" from the bus1 column
pv.df$bus1 <- gsub("bus1=", "", pv.df$bus1)
pv.df$phases <- gsub("phases=", "", pv.df$phases)
pv.df$kV <- gsub("kV=", "", pv.df$kV)
pv.df$kVA <- gsub("kVA=", "", pv.df$kVA)
pv.df$pmpp <- gsub("pmpp=", "", pv.df$pmpp)
pv.df$percentCutout <- gsub("percentCutout=", "", pv.df$percentCutout)
pv.df$percentCutin <- gsub("percentCutin=", "", pv.df$percentCutin)
pv.df$pf <- gsub("pf=", "", pv.df$pf)

# remove the characters after the first "." in the columns bus1 and bus2
pv.df$bus1 <- gsub("\\..*", "", pv.df$bus1)

# ensure every bus in bus1 and bus2 is in buses.df and remove any that are not # 5 removed
buses.df <- readRDS("./exports/buses_df.rds")
pv.df <- pv.df %>% filter(bus1 %in% buses.df$bus) # none removed

# remove any duplicate pv based on bus1
# nevermind, this removes 117 of them
# pv.df <- pv.df %>% distinct(bus1, .keep_all = TRUE)

# export
saveRDS(pv.df, "./exports/pv_df.rds")
```
